version: '3.1'

services:
  postgresql:
    image: postgres
    container_name: pg
    ports:
      - 5432:5432
    volumes: 
      - ./Chinook_PostgreSql_utf8.sql:/docker-entrypoint-initdb.d/0_init.sql
      #- ./pg/data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=test